//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Src.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Oprator
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public int RoleID { get; set; }
        public string Phone { get; set; }
        public string Pass { get; set; }
        public string NatCode { get; set; }
        public Nullable<byte> RFCount { get; set; }
        public Nullable<System.DateTime> BDate { get; set; }
        public bool Status { get; set; }
    
        public virtual Tbl_OPRole Tbl_OPRole { get; set; }
    }
}
