//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Src.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Factor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Factor()
        {
            this.Tbl_FactProc = new HashSet<Tbl_FactProc>();
        }
    
        public int ID { get; set; }
        public int CustID { get; set; }
        public long TotalPrice { get; set; }
        public bool IsPrint { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<byte> CancelReason { get; set; }
        public string TrackingCode { get; set; }
        public string TipaxCode { get; set; }
        public bool PaymentStatus { get; set; }
        public byte Status { get; set; }
    
        public virtual Tbl_CustAddress Tbl_CustAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FactProc> Tbl_FactProc { get; set; }
        public virtual Tbl_Customer Tbl_Customer { get; set; }
    }
}
