//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Src.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ProcCat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_ProcCat()
        {
            this.Tbl_PCPGroup = new HashSet<Tbl_PCPGroup>();
            this.Tbl_ProcCat1 = new HashSet<Tbl_ProcCat>();
            this.Tbl_Product = new HashSet<Tbl_Product>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string EnTitle { get; set; }
        public string SeoDesc { get; set; }
        public Nullable<int> PID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PCPGroup> Tbl_PCPGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ProcCat> Tbl_ProcCat1 { get; set; }
        public virtual Tbl_ProcCat Tbl_ProcCat2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Product> Tbl_Product { get; set; }
    }
}
