//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Src.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Product()
        {
            this.Tbl_FactProc = new HashSet<Tbl_FactProc>();
            this.Tbl_ProcImg = new HashSet<Tbl_ProcImg>();
            this.Tbl_ProcProp = new HashSet<Tbl_ProcProp>();
            this.Tbl_ProcReview = new HashSet<Tbl_ProcReview>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string ShortDesc { get; set; }
        public string FullDesc { get; set; }
        public string TopProp { get; set; }
        public byte Rate { get; set; }
        public long Price { get; set; }
        public long OffPrice { get; set; }
        public Nullable<int> OffID { get; set; }
        public int BrandID { get; set; }
        public int CatID { get; set; }
        public int Count { get; set; }
        public Nullable<int> VisitCount { get; set; }
        public byte Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FactProc> Tbl_FactProc { get; set; }
        public virtual Tbl_ProcBrand Tbl_ProcBrand { get; set; }
        public virtual Tbl_ProcCat Tbl_ProcCat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ProcImg> Tbl_ProcImg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ProcProp> Tbl_ProcProp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ProcReview> Tbl_ProcReview { get; set; }
    }
}
