//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Src.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Page
    {
        public int ID { get; set; }
        public string TItle { get; set; }
        public string SeoDesc { get; set; }
        public string Body { get; set; }
        public bool Status { get; set; }
    }
}
