//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Src.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Payment
    {
        public int ID { get; set; }
        public int FactID { get; set; }
        public string TrackingCode { get; set; }
        public System.DateTime Date { get; set; }
        public string BankName { get; set; }
        public string BankStatus { get; set; }
        public long Price { get; set; }
        public string IP { get; set; }
        public byte Status { get; set; }
    
        public virtual Tbl_Factor Tbl_Factor { get; set; }
    }
}
