//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Src.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ProcReview
    {
        public int ProcID { get; set; }
        public int CustID { get; set; }
        public byte Rate { get; set; }
        public string Subject { get; set; }
        public string Review { get; set; }
        public bool Status { get; set; }
    
        public virtual Tbl_Product Tbl_Product { get; set; }
        public virtual Tbl_Customer Tbl_Customer { get; set; }
    }
}
