//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Src.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PCPGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_PCPGroup()
        {
            this.Tbl_PCPGroup1 = new HashSet<Tbl_PCPGroup>();
            this.Tbl_ProcProp = new HashSet<Tbl_ProcProp>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int PID { get; set; }
        public int CatID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PCPGroup> Tbl_PCPGroup1 { get; set; }
        public virtual Tbl_PCPGroup Tbl_PCPGroup2 { get; set; }
        public virtual Tbl_ProcCat Tbl_ProcCat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ProcProp> Tbl_ProcProp { get; set; }
    }
}
