//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Src.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_APermission
    {
        public int ID { get; set; }
        public int RoleID { get; set; }
        public int ModuleID { get; set; }
        public Nullable<bool> Read_Write { get; set; }
        public Nullable<bool> Delete { get; set; }
    }
}
