//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Src.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Menu()
        {
            this.Tbl_Menu1 = new HashSet<Tbl_Menu>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PID { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public Nullable<int> Sort { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Menu> Tbl_Menu1 { get; set; }
        public virtual Tbl_Menu Tbl_Menu2 { get; set; }
    }
}
